package:
  name: fly_conda_test
  version: "0.11.1"

source:
  path: ..

build:
  # noarch: python
  script: maturin build --release && pip install .

requirements:
  host:
    - python
    - pip
    - maturin
    - rust
  run:
    - python
    - anaconda::cudatoolkit
    - cupy # [linux]
    - cupy # [win]
    - balbasty::cupy # [osx]
    - bioconda::mgltools # [linux]
    - bioconda::mgltools # [osx]
    - conda-forge::smina # [linux]
    - conda-forge::smina # [osx]

about:
  home: https://github.com/dhnchandan/fly-conda-test-feedstock.git
  license: MIT
  license_file: LICENSE
  summary: "Test anaconda package"

extra:
  recipe-maintainers:
    - dhnchandan