name: fly_conda_build_environment

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - setuptools
  - conda-build
  - anaconda-client
  - rust
  - cudatoolkit
  - cupy
  - pip
  - pip:
    - -r requirements.txt