name: fly_conda_build_environment

channels:
  - defaults
  - conda-forge
  - bioconda

dependencies:
  - python=3.9
  - setuptools
  - conda-build
  - anaconda-client
  - cudatoolkit
  - cupy
  - smina
  - mgltools
  - pip
  - pip:
    - -r requirements.txt