name: Build and Upload Conda Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_NAME: fly_conda_test
  BUILD_VERSION: 0.3.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Install conda-build
        run: conda install conda-build

      - name: Build the package
        run: conda-build recipe

      - name: Upload package to Anaconda.org
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: anaconda upload ~/miniconda3/conda-bld/noarch/${{ BUILD_NAME }}-${{ BUILD_VERSION }}-py_0.tar.bz2 -u firesimulations
