name: Build and Upload Conda Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_NAME: fly_conda_build_environment

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Create Conda environment
        run: conda env create -f environment.yml

      - name: Build the package
        run: |
          conda activate ${{ env.BUILD_NAME }}
          conda build . --output-folder ${{ github.workspace }}/conda-bld

      - name: Upload package to Anaconda.org (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: anaconda upload ${{ github.workspace }}/conda-bld/noarch/*.tar.bz2 -u firesimulations
        shell: bash

      - name: Upload package to Anaconda.org (Mac)
        if: matrix.os == 'macos-latest'
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: anaconda upload ${{ github.workspace }}/conda-bld/noarch/*.tar.bz2 -u firesimulations
        shell: bash

      - name: Upload package to Anaconda.org (Windows)
        if: matrix.os == 'windows-latest'
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: anaconda upload %GITHUB_WORKSPACE%\\conda-bld\\noarch\\*.tar.bz2 -u firesimulations
        shell: cmd
